<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Place;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $places = [
            [
                'id' => 'sigiriya_lion_rock',
                'name' => 'Sigiriya Lion Rock Fortress',
                'description' => 'Ancient 5th-century rock fortress and palace built by King Kasyapa, featuring world-famous frescoes, mirror walls, and sophisticated water gardens.',
                'district' => 'Matale',
                'province' => 'Central Province',
                'category' => 'historical',
                'lat' => 7.9570,
                'lng' => 80.7603,
                'rating' => 4.9,
                'ticket_range' => 'Moderate',
                'ticket_price' => 'LKR 10000 (Foreign) / LKR 100 (Local)',
                'opening_hours' => '6:30 AM - 5:30 PM',
                'mobile_signal' => '4G Good',
                'road_type' => 'Paved Highway',
                'road_condition' => 'Excellent',
                'vehicle_access' => 'All Vehicles',
                'activities' => 'Rock climbing, Photography, Archaeological exploration, Bird watching',
                'tourist_popularity' => 'High',
                'family_friendly' => 'Yes (Supervision needed on stairs)',
                'budget_category' => 'Premium',
                'parking_avail' => 'Available',
                'parking_range' => 'Ample Parking Site',
                'toilets' => 'Available at entrance',
                'food_nearby' => 'Cafes & Restaurants within 1 km',
                'wheelchair_access' => 'Gardens only',
                'camping_allowed' => 'No',
                'safety_level' => 'High (Follow guard rails)',
                'wildlife_hazard' => 'Beware of hornets',
                'guide_required' => 'Optional',
                'rain_sensitivity' => 'Moderate (Steps can be slippery)',
                'monsoon_note' => 'North-East monsoon rains November to January',
                'best_time' => 'Early Morning (6:30 AM - 9:00 AM)',
                'best_time_to_visit' => 'January to April',
                'height_m' => '200m above plain',
                'length_km' => '3 km circuit',
                'surfing' => 'No',
                'risk_tags' => json_encode(['steep_climb', 'hornet_hazard', 'high_heat']),
                'facilities' => json_encode(['restrooms', 'museum', 'parking', 'souvenir_shops']),
                'ar_supported' => true,
                'ar_tier' => 1,
                'ar_brand_name' => 'Sigiriya Royal Palace 3D',
                'ar_model_url' => 'https://cdn.hiddengemssl.com/models/sigiriya.glb',
                'ar_historical_model_url' => 'https://cdn.hiddengemssl.com/models/sigiriya_5th_century.glb',
                'ar_model_scale' => 0.0150,
                'historical_period' => 'Anuradhapura Period (5th Century AD)',
                'ar_file_size_mb' => 14.50,
                'audio_guide_url_si' => 'https://cdn.hiddengemssl.com/audio/sigiriya_si.mp3',
                'audio_guide_url_en' => 'https://cdn.hiddengemssl.com/audio/sigiriya_en.mp3',
                'geohash' => 'tc3x1v',
                'image_url' => 'https://images.unsplash.com/photo-1588598175944-4f81a7b458d9?w=800&q=80',
                'sync_version' => 1,
                'is_deleted' => false,
            ],
            [
                'id' => 'nine_arch_bridge',
                'name' => 'Nine Arch Bridge Demodara',
                'description' => 'Colonial-era railway viaduct constructed entirely from rocks, bricks, and cement without a single piece of steel, nestled amidst lush tea estates.',
                'district' => 'Badulla',
                'province' => 'Uva Province',
                'category' => 'architecture',
                'lat' => 6.8768,
                'lng' => 81.0608,
                'rating' => 4.8,
                'ticket_range' => 'Free',
                'ticket_price' => 'Free Access',
                'opening_hours' => '24 Hours (Best sunrise to sunset)',
                'mobile_signal' => '4G Moderate',
                'road_type' => 'Narrow Hill Path / TukTuk access',
                'road_condition' => 'Moderate (Downhill walk)',
                'vehicle_access' => 'TukTuk / Foot only to bridge',
                'activities' => 'Train spotting, Hiking, Photography, Tea estate walks',
                'tourist_popularity' => 'Very High',
                'family_friendly' => 'Yes',
                'budget_category' => 'Budget',
                'parking_avail' => 'Limited near junction',
                'parking_range' => 'Roadside parking 1km away',
                'toilets' => 'Available at local cafes',
                'food_nearby' => 'Numerous cafes overlooking bridge',
                'wheelchair_access' => 'No',
                'camping_allowed' => 'No',
                'safety_level' => 'Moderate (Keep off tracks when train approaches)',
                'wildlife_hazard' => 'Leeches during rainy days',
                'guide_required' => 'No',
                'rain_sensitivity' => 'High (Muddy pathways)',
                'monsoon_note' => 'October to December rainy season',
                'best_time' => 'Morning (9:00 AM for train crossing)',
                'best_time_to_visit' => 'All year round',
                'height_m' => '24m high',
                'length_km' => '91m length',
                'surfing' => 'No',
                'risk_tags' => json_encode(['active_railway', 'steep_edges', 'leeches_in_rain']),
                'facilities' => json_encode(['viewpoint_cafes', 'coconut_stalls']),
                'ar_supported' => false,
                'ar_tier' => 3,
                'geohash' => 'tc1h3w',
                'image_url' => 'https://images.unsplash.com/photo-1546708973-b339540b5162?w=800&q=80',
                'sync_version' => 2,
                'is_deleted' => false,
            ],
            [
                'id' => 'mirissa_secret_beach',
                'name' => 'Mirissa Secret Beach',
                'description' => 'Secluded tropical cove split into two natural tidal pools surrounded by palm trees and volcanic rock formations, ideal for tranquil swimming.',
                'district' => 'Matara',
                'province' => 'Southern Province',
                'category' => 'beaches',
                'lat' => 5.9449,
                'lng' => 80.4504,
                'rating' => 4.7,
                'ticket_range' => 'Free',
                'ticket_price' => 'Free Access',
                'opening_hours' => '6:00 AM - 7:00 PM',
                'mobile_signal' => '4G Excellent',
                'road_type' => 'Steep narrow lane',
                'road_condition' => 'Rough in last 300m',
                'vehicle_access' => 'TukTuk or Scooter',
                'activities' => 'Snorkeling, Sunbathing, Tidal pool swimming, Sunset viewing',
                'tourist_popularity' => 'Moderate',
                'family_friendly' => 'Yes (Natural shallow pool)',
                'budget_category' => 'Budget',
                'parking_avail' => 'Limited scooter parking',
                'parking_range' => 'Top of hill parking',
                'toilets' => 'Available at Secret Beach Bar',
                'food_nearby' => 'Secret Beach Bar & Restaurant',
                'wheelchair_access' => 'No',
                'camping_allowed' => 'No',
                'safety_level' => 'High in rock pools, caution in open ocean',
                'wildlife_hazard' => 'Sea urchins near rocks',
                'guide_required' => 'No',
                'rain_sensitivity' => 'Low',
                'monsoon_note' => 'South-West monsoon May to September brings high waves outside reef',
                'best_time' => 'Late afternoon (4:00 PM - 6:30 PM)',
                'best_time_to_visit' => 'November to April',
                'height_m' => 'Sea level',
                'length_km' => '0.5 km coastline',
                'surfing' => 'Nearby at Mirissa main reef',
                'risk_tags' => json_encode(['sea_urchins', 'slippery_rocks']),
                'facilities' => json_encode(['beach_bar', 'sunbeds', 'showers']),
                'ar_supported' => false,
                'ar_tier' => 3,
                'geohash' => 'tc0p3q',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
                'sync_version' => 3,
                'is_deleted' => false,
            ],
            [
                'id' => 'ravana_falls_ella',
                'name' => 'Ravana Falls',
                'description' => 'Dramatic 25-meter cascading waterfall tied to the legendary Ramayana epic, cascading down oval-shaped concave rock formations beside the main mountain highway.',
                'district' => 'Badulla',
                'province' => 'Uva Province',
                'category' => 'waterfalls',
                'lat' => 6.8410,
                'lng' => 81.0543,
                'rating' => 4.6,
                'ticket_range' => 'Free',
                'ticket_price' => 'Free Access',
                'opening_hours' => '24 Hours',
                'mobile_signal' => '4G Good',
                'road_type' => 'Well-paved Highway (Ella-Wellawaya Road)',
                'road_condition' => 'Excellent',
                'vehicle_access' => 'All Vehicles & Buses',
                'activities' => 'Sightseeing, Photography, Street food sampling, Waterfall viewing',
                'tourist_popularity' => 'Very High',
                'family_friendly' => 'Yes (Viewpoint area)',
                'budget_category' => 'Budget',
                'parking_avail' => 'Roadside parking slots',
                'parking_range' => 'Moderate along highway curves',
                'toilets' => 'Public restrooms nearby',
                'food_nearby' => 'Street corn & mango vendors, cafes nearby',
                'wheelchair_access' => 'Viewpoint accessible from road',
                'camping_allowed' => 'No',
                'safety_level' => 'Moderate (Do not climb wet rocks)',
                'wildlife_hazard' => 'Macaque monkeys (secure personal belongings)',
                'guide_required' => 'No',
                'rain_sensitivity' => 'High (Flash floods possible during heavy downpours)',
                'monsoon_note' => 'Most thunderous November to January',
                'best_time' => 'Morning or Late Afternoon',
                'best_time_to_visit' => 'All year round',
                'height_m' => '25m fall height',
                'length_km' => 'N/A',
                'surfing' => 'No',
                'risk_tags' => json_encode(['slippery_rocks', 'monkeys', 'highway_traffic']),
                'facilities' => json_encode(['souvenir_stalls', 'food_stalls', 'viewpoint']),
                'ar_supported' => false,
                'ar_tier' => 3,
                'geohash' => 'tc1h1j',
                'image_url' => 'https://images.unsplash.com/photo-1432462770865-65b70566d673?w=800&q=80',
                'sync_version' => 4,
                'is_deleted' => false,
            ],
            [
                'id' => 'pidurangala_rock',
                'name' => 'Pidurangala Rock Summit',
                'description' => 'Rugged wilderness peak offering the most breathtaking panoramic view directly facing Sigiriya Lion Rock, passing through an ancient cavern temple and reclining Buddha.',
                'district' => 'Matale',
                'province' => 'Central Province',
                'category' => 'adventure',
                'lat' => 7.9645,
                'lng' => 80.7635,
                'rating' => 4.9,
                'ticket_range' => 'Budget',
                'ticket_price' => 'LKR 1000',
                'opening_hours' => '5:00 AM - 6:00 PM',
                'mobile_signal' => '4G Moderate',
                'road_type' => 'Paved secondary road',
                'road_condition' => 'Good',
                'vehicle_access' => 'Cars, TukTuks, Vans',
                'activities' => 'Sunrise hiking, Boulder scrambling, Panoramic photography, Meditation',
                'tourist_popularity' => 'High',
                'family_friendly' => 'Moderate (Top section requires climbing over boulders)',
                'budget_category' => 'Budget',
                'parking_avail' => 'Available at temple entrance',
                'parking_range' => 'Spacious parking area',
                'toilets' => 'Available at base temple',
                'food_nearby' => 'Refreshment stalls at base',
                'wheelchair_access' => 'No',
                'camping_allowed' => 'No',
                'safety_level' => 'Moderate (Unfenced rocky summit)',
                'wildlife_hazard' => 'Snakes in dense undergrowth at dawn',
                'guide_required' => 'No',
                'rain_sensitivity' => 'High (Rocks become extremely slippery)',
                'monsoon_note' => 'North-East monsoon rains October to January',
                'best_time' => 'Pre-dawn (5:15 AM for sunrise)',
                'best_time_to_visit' => 'January to September',
                'height_m' => '200m climb',
                'length_km' => '1.5 km trail',
                'surfing' => 'No',
                'risk_tags' => json_encode(['steep_boulders', 'unfenced_summit', 'dark_trail_at_dawn']),
                'facilities' => json_encode(['temple_base', 'parking', 'shoe_storage']),
                'ar_supported' => false,
                'ar_tier' => 3,
                'geohash' => 'tc3x1y',
                'image_url' => 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&q=80',
                'sync_version' => 5,
                'is_deleted' => false,
            ],
            [
                'id' => 'knuckles_mountain_range',
                'name' => 'Knuckles Conservation Forest',
                'description' => 'UNESCO World Heritage cloud forest featuring five jagged peaks resembling closed knuckles, harboring endemic flora, rare lizards, and crystal-clear mountain streams.',
                'district' => 'Matale / Kandy',
                'province' => 'Central Province',
                'category' => 'wildlife_hiking',
                'lat' => 7.4667,
                'lng' => 80.7833,
                'rating' => 4.9,
                'ticket_range' => 'Moderate',
                'ticket_price' => 'LKR 3000 Forest Conservation Permit',
                'opening_hours' => '6:00 AM - 5:00 PM',
                'mobile_signal' => 'Patchy / None inside forest',
                'road_type' => 'Mountain dirt trail & narrow paved tracks',
                'road_condition' => 'Rough / 4WD recommended for deeper trails',
                'vehicle_access' => '4x4 Jeep / High clearance vehicles',
                'activities' => 'Multi-day trekking, Bird watching, Waterfall swimming, Camping',
                'tourist_popularity' => 'Moderate',
                'family_friendly' => 'Older teens / Fit hikers',
                'budget_category' => 'Moderate',
                'parking_avail' => 'Trailhead parking',
                'parking_range' => 'At forest checkpoints',
                'toilets' => 'Basic forest office toilets',
                'food_nearby' => 'Bring all provisions & water',
                'wheelchair_access' => 'No',
                'camping_allowed' => 'Yes (With designated permits)',
                'safety_level' => 'Moderate (Wilderness navigation required)',
                'wildlife_hazard' => 'Leeches, Leopards, Wild Buffalo',
                'guide_required' => 'Highly Recommended / Required by forest dept for certain trails',
                'rain_sensitivity' => 'High (Dense fog and rapid stream swelling)',
                'monsoon_note' => 'Heavy rains November to February',
                'best_time' => 'Early Morning departure',
                'best_time_to_visit' => 'March to September',
                'height_m' => '1863m peak elevation',
                'length_km' => '15+ km trail networks',
                'surfing' => 'No',
                'risk_tags' => json_encode(['leeches', 'fog_disorientation', 'no_cellular_signal', 'remote_area']),
                'facilities' => json_encode(['campsites', 'trailhead_office']),
                'ar_supported' => false,
                'ar_tier' => 3,
                'geohash' => 'tc3q8m',
                'image_url' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
                'sync_version' => 6,
                'is_deleted' => false,
            ]
        ];

        $currentMaxSync = Place::max('sync_version') ?? 0;
        foreach ($places as $data) {
            $existing = Place::find($data['id']);
            if ($existing) {
                unset($data['sync_version']);
                $existing->update($data);
            } else {
                $currentMaxSync++;
                $data['sync_version'] = $currentMaxSync;
                Place::create($data);
            }
        }
    }
}
