import 'package:hidden_gems_sl/core/theme/app_theme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../core/theme/oracle_ui_system.dart';
import '../../data/models/tour_review.dart';
import '../../data/repositories/review_repository.dart';
import '../../l10n/app_localizations.dart';

class ReviewSubmissionScreen extends ConsumerStatefulWidget {
  final String sessionId;
  final String guideId;
  final String touristId;
  const ReviewSubmissionScreen({
    super.key, 
    required this.sessionId, 
    required this.guideId, 
    required this.touristId
  });

  @override
  ConsumerState<ReviewSubmissionScreen> createState() => _ReviewSubmissionScreenState();
}

class _ReviewSubmissionScreenState extends ConsumerState<ReviewSubmissionScreen> {
  double _overallRating = 5.0;
  double _knowledgeRating = 5.0;
  double _communicationRating = 5.0;
  double _punctualityRating = 5.0;
  double _safetyRating = 5.0;
  final double _friendlinessRating = 5.0;
  final TextEditingController _commentController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _commentController.dispose();
    super.dispose();
  }

  Future<void> _handleSubmit() async {
    setState(() => _isSubmitting = true);
    try {
      final review = TourReview(
        reviewId: '', // Generated by repository
        sessionId: widget.sessionId,
        guideId: widget.guideId,
        touristId: widget.touristId,
        overallRating: _overallRating,
        knowledgeRating: _knowledgeRating,
        communicationRating: _communicationRating,
        punctualityRating: _punctualityRating,
        safetyRating: _safetyRating,
        friendlinessRating: _friendlinessRating,
        comment: _commentController.text,
        createdAt: DateTime.now(),
        submittedFromDeviceHash: 'DEVICE_HASH_SAMPLE', // In reality, get device info
      );

      await ref.read(reviewRepositoryProvider).submitReview(review);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(AppLocalizations.of(context)!.reviewSubmitSuccessMessage)),
      );
      Navigator.pop(context);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(AppLocalizations.of(context)!.reviewSubmitErrorMessage(e.toString())), backgroundColor: AppTheme.colors.red),
      );
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return Scaffold(
      body: OracleUI.auraBackground(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(28),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 48),
              _buildHeader(l10n),
              const SizedBox(height: 40),
              _buildRatingSection(l10n.overallExperienceLabel, _overallRating, (v) => setState(() => _overallRating = v)),
              const SizedBox(height: 32),
              _buildFactorGrid(l10n),
              const SizedBox(height: 40),
              _buildCommentSection(l10n),
              const SizedBox(height: 48),
              _buildSubmitButton(l10n),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildHeader(AppLocalizations l10n) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        IconButton(
          onPressed: () => Navigator.pop(context),
          icon: Icon(Icons.close_rounded, color: AppTheme.colors.white, size: 28),
        ),
        const SizedBox(height: 24),
        OracleUI.neonText(
          l10n.missionFeedbackEyebrow,
          style: GoogleFonts.outfit(fontSize: 12, fontWeight: FontWeight.w900, letterSpacing: 4, color: AppTheme.colors.white24),
        ),
        const SizedBox(height: 8),
        Text(
          l10n.rateGuidePerformanceTitle,
          style: GoogleFonts.outfit(color: AppTheme.colors.white, fontSize: 28, fontWeight: FontWeight.w900),
        ).animate().fadeIn().slideY(begin: 0.1),
        const SizedBox(height: 12),
        Text(
          l10n.trustScoreDisclaimer,
          style: GoogleFonts.inter(color: AppTheme.colors.white10, fontSize: 13, fontWeight: FontWeight.bold),
        ),
      ],
    );
  }

  Widget _buildRatingSection(String title, double value, Function(double) onChanged) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w900, letterSpacing: 2, color: AppTheme.colors.white60),
        ),
        const SizedBox(height: 24),
        Center(
          child: Column(
            children: [
              Text(
                value.toStringAsFixed(1),
                style: GoogleFonts.outfit(fontSize: 64, fontWeight: FontWeight.w900, color: Theme.of(context).colorScheme.primary),
              ).animate(target: value).scale(begin: const Offset(1, 1), end: const Offset(1.1, 1.1), duration: 200.ms),
              const SizedBox(height: 16),
              Slider(
                value: value,
                min: 1.0,
                max: 5.0,
                divisions: 4,
                activeColor: Theme.of(context).colorScheme.primary,
                inactiveColor: AppTheme.colors.white.withValues(alpha: 0.05),
                onChanged: onChanged,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(AppLocalizations.of(context)!.ratingScaleAverageLabel, style: GoogleFonts.inter(color: AppTheme.colors.white10, fontSize: 10, fontWeight: FontWeight.bold)),
                  Text(AppLocalizations.of(context)!.ratingScaleExceptionalLabel, style: GoogleFonts.inter(color: AppTheme.colors.white10, fontSize: 10, fontWeight: FontWeight.bold)),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildFactorGrid(AppLocalizations l10n) {
    return GridView.count(
      crossAxisCount: 2,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      mainAxisSpacing: 16,
      crossAxisSpacing: 16,
      childAspectRatio: 1.5,
      children: [
        _buildFactorItem(l10n.knowledgeFactorLabel, _knowledgeRating, (v) => setState(() => _knowledgeRating = v)),
        _buildFactorItem(l10n.communicationFactorLabel, _communicationRating, (v) => setState(() => _communicationRating = v)),
        _buildFactorItem(l10n.punctualityFactorLabel, _punctualityRating, (v) => setState(() => _punctualityRating = v)),
        _buildFactorItem(l10n.safetyFactorLabel, _safetyRating, (v) => setState(() => _safetyRating = v)),
      ],
    ).animate().fadeIn(delay: 400.ms);
  }

  Widget _buildFactorItem(String label, double value, Function(double) onChanged) {
    return OracleUI.glassContainer(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      borderRadius: BorderRadius.circular(16),
      borderColor: AppTheme.colors.white.withValues(alpha: 0.05),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(fontSize: 10, fontWeight: FontWeight.w900, color: AppTheme.colors.white24, letterSpacing: 1),
          ),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              IconButton(
                onPressed: () => value > 1 ? onChanged(value - 1) : null,
                icon: Icon(Icons.remove_rounded, color: AppTheme.colors.white10, size: 20),
              ),
              Text(
                value.toInt().toString(),
                style: GoogleFonts.outfit(fontSize: 20, fontWeight: FontWeight.w900, color: AppTheme.colors.white),
              ),
              IconButton(
                onPressed: () => value < 5 ? onChanged(value + 1) : null,
                icon: Icon(Icons.add_rounded, color: AppTheme.colors.white10, size: 20),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildCommentSection(AppLocalizations l10n) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          l10n.fieldNotesLabelUppercase,
          style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w900, letterSpacing: 2, color: AppTheme.colors.white60),
        ),
        const SizedBox(height: 16),
        OracleUI.glassContainer(
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
          borderRadius: BorderRadius.circular(20),
          borderColor: AppTheme.colors.white.withValues(alpha: 0.05),
          child: TextField(
            controller: _commentController,
            maxLines: 4,
            style: TextStyle(color: AppTheme.colors.white),
            decoration: InputDecoration(
              hintText: l10n.commentFieldHint,
              hintStyle: GoogleFonts.inter(color: AppTheme.colors.white12, fontSize: 13, height: 1.5),
              border: InputBorder.none,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSubmitButton(AppLocalizations l10n) {
    return SizedBox(
      width: double.infinity,
      height: 64,
      child: ElevatedButton(
        onPressed: _isSubmitting ? null : _handleSubmit,
        style: ElevatedButton.styleFrom(
          backgroundColor: Theme.of(context).colorScheme.primary,
          foregroundColor: AppTheme.colors.black,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          elevation: 20,
          shadowColor: Theme.of(context).colorScheme.primary.withValues(alpha: 0.3),
        ),
        child: _isSubmitting
          ? CircularProgressIndicator(color: AppTheme.colors.black)
          : Text(
              l10n.transmitFeedbackButton,
              style: GoogleFonts.outfit(fontSize: 16, fontWeight: FontWeight.w900, letterSpacing: 2),
            ),
      ).animate(onPlay: (c) => c.repeat()).shimmer(duration: 3.seconds, color: AppTheme.colors.white24),
    );
  }
}
